### ISSUE TITLE
Error when B=1

### ISSUE THREAD

**Issue by hankcs** [occasumlux/WuManber#1]
Hi,

I found this implementation will make mistake when choosing B=1 with these patterns and text:

```
int main()
{
  //Vector that stores the patterns to search
  std::vector<std::string> v;
  v.push_back("01000");
  v.push_back("00011");


  //Wu Manber -wrapper- class
  WuManber wu;

  //Construction of the tables required by the algorithm
  wu.initialize(v);

  //List with the detail of every match found
  auto hits = wu.search("0000110000", 0);
  for (auto& hit : hits)
  {
    std::cout << hit.pattern << std::endl;
  }
  return 0;
}
```

This is obviously wrong. But if we choose `B=2`, it can find the correct answer, which is `00011`.  According to the papers, the B value should not affect answers if only `B<=m`.

**Comment by hankcs** [comment]
Actually I'm quite suspicious of Oh et al. (2014)'s paper. They said 

>  The auxiliary shift value (AS, for short) is the minimum among the shift distances of an
entry calculated from P , excluding patterns having the relevant entry as their suffix.

And for example:

<img width="536" alt="hankcs com 2018-01-17 6 43 47" src="https://user-images.githubusercontent.com/5326890/35053536-f421492e-fb6f-11e7-9058-cd4e570754c9.png">

The said `ASHIFT[er]=4`, but according to their definition, ASHIFT of "er" should be `1`, which comes from `ancert`, the only word not ending with "er". I'm quite confused about the proposed idea of this paper, is it correct?

**Comment by occasumlux** [comment]
It's 4 because you only take the m first characters of each pattern to make the tables, in this case m = 5, so "ancert" becomes "ancer" and every pattern ends in "er".

Cheers!

**Comment by occasumlux** [comment]
Fixed!
@hankcs

**Comment by hankcs** [comment]
Thanks for your explanation, I'll go over that paper again.

**Comment by hankcs** [comment]
Oh I got your idea!

As every pattern ends with "er", we excluded all of them. The ASHIFT is `m-B+1`. Here we have `m=5`, `B=2`, so ASHIFT is `4`.
