### ISSUE TITLE
std::out_of_range occured when B=3

### ISSUE THREAD

**Issue by hankcs** [occasumlux/WuManber#2]
Hi,

I also found a bug when choosing `B=3`, which is a common parameter according the paper. I call it a bug because it is more serious which terminates the program. Same main function:

```
int main()
{
  //Vector that stores the patterns to search
  std::vector<std::string> v;
  v.push_back("01000");
  v.push_back("00011");


  //Wu Manber -wrapper- class
  WuManber wu;

  //Construction of the tables required by the algorithm
  wu.initialize(v);

  //List with the detail of every match found
  auto hits = wu.search("0000110000", 0);
  for (auto& hit : hits)
  {
    std::cout << hit.pattern << std::endl;
  }
  return 0;
}
```

libc++abi.dylib: terminating with uncaught exception of type std::out_of_range: basic_string

**Comment by occasumlux** [comment]
Hi!

Sorry for the delay in the response, I'll review the code to see what's happening

**Comment by occasumlux** [comment]
Fixed!

**Comment by hankcs** [comment]
Thanks, nice job!
